DROP TABLE DOCS;
DROP TABLE sportsTable;
DROP TABLE reserveFundsOPS;
DROP TABLE reserveFundsOPSPosition;
DROP TABLE  reserveFundsOPSExpenses;
DROP TABLE transfersIn;
DROP TABLE transfersOut;
DROP TABLE expenses;
DROP TABLE reserveFund;




CREATE TABLE DOCS(ROLE VARCHAR(30), ID INT AUTO_INCREMENT, FORM INT, CONSTRAINT PK_DOCS PRIMARY KEY(ROLE, ID, FORM));

CREATE TABLE uwide (ID INT, ROLE VARCHAR(30),DEPARTMENT VARCHAR(30), SB1 VARCHAR(25), OPS1 VARCHAR(25), OPSGA1 VARCHAR(25), OPSACA1 VARCHAR(25), EXP1 VARCHAR(25),
SB2 VARCHAR(25), OPS2 VARCHAR(25), OPSGA2 VARCHAR(25), OPSACA2 VARCHAR(25), EXP2 VARCHAR(25),
SB3 VARCHAR(25), OPS3 VARCHAR(25), OPSGA3 VARCHAR(25), OPSACA3 VARCHAR(25), EXP3 VARCHAR(25),FOREIGN KEY(ID, ROLE) REFERENCES DOCS(ID,ROLE), CONSTRAINT PK_UWIDE PRIMARY KEY(ID, ROLE, DEPARTMENT));


CREATE TABLE reserveFund (ID INT , ROLE VARCHAR(30), P_TIN INT, P_EXP INT, P_OUT INT, T_INT_COMMENT VARCHAR(255), EXP_COMMENT_1 VARCHAR(255),  EXP_COMMENT_2 VARCHAR(255), EXP_COMMENT_3 VARCHAR(255), EXP_COMMENT_4 VARCHAR(255), T_OUT_COMMENT VARCHAR(255),FOREIGN KEY (ID, ROLE) REFERENCES DOCS(ID,ROLE), CONSTRAINT PK_RESERVEFUND PRIMARY KEY (ID,ROLE));

CREATE TABLE transfersIn (ROLE VARCHAR(30),T_ID INT, NAME VARCHAR(25), AMOUNT INT, FOREIGN KEY (T_ID,ROLE) REFERENCES DOCS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_TIN PRIMARY KEY (ROLE,T_ID, NAME));
CREATE TABLE transfersOut (ROLE VARCHAR(30),T_ID INT, NAME VARCHAR(25), AMOUNT INT, FOREIGN KEY (T_ID) REFERENCES reserveFund(ID) ON DELETE CASCADE, CONSTRAINT PK_TOUT PRIMARY KEY (T_ID, NAME));
CREATE TABLE expenses (ROLE VARCHAR(30), T_ID INT, NAME VARCHAR(25), AMOUNT INT,FOREIGN KEY (T_ID) REFERENCES reserveFund(ID) ON DELETE CASCADE, CONSTRAINT PK_TOUT PRIMARY KEY (T_ID, NAME));






CREATE TABLE reserveFundsOPS(ROLE VARCHAR(30),ID INT, REVENUE VARCHAR(9), REVENUE_COMMENT VARCHAR(255), OPS VARCHAR(9), OPS_COMMENT VARCHAR(255), T_IN VARCHAR(9), T_IN_COMMENT VARCHAR(255), T_OUT VARCHAR(9), T_OUT_COMMENT VARCHAR(255), FOREIGN KEY (ROLE, ID) REFERENCES DOCS(ROLE, ID), CONSTRAINT PK_RESERVEOPS PRIMARY KEY (ID,ROLE));

CREATE TABLE reserveFundsOPSPosition (ROLE VARCHAR(55),T_ID INT, TITLE VARCHAR(50), FAUSTUDENT VARCHAR(3), HOURLYRATE VARCHAR(9), HOURS_WEEK VARCHAR(9), WEEKS_YEAR VARCHAR(9),PEOPLE_IN_POSITION VARCHAR(9), FOREIGN KEY (T_ID,ROLE) REFERENCES reserveFundsOPS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_POSITION PRIMARY KEY (T_ID, TITLE));

CREATE TABLE reserveFundsOPSExpenses(ROLE VARCHAR(55),T_ID INT, SUPPORT VARCHAR(255), FOOD VARCHAR(255), PROGRAMS VARCHAR(255), OTHER VARCHAR(255), FOREIGN KEY (ROLE, T_ID) REFERENCES reserveFundsOPS(ROLE,ID), CONSTRAINT PK_EXPENSES PRIMARY KEY (ROLE,T_ID));





CREATE TABLE operatingFund (ROLE VARCHAR(30), ID INT, SMARTTAG VARCHAR(30), ACCOUNTMANAGER VARCHAR(30), STUDENTBUDGET VARCHAR(30), MANAGER_NAME VARCHAR(30), MANAGER_EMAIL VARCHAR(30), MANAGER_TELEPHONE VARCHAR(9), MANAGER_SIGNATURE VARCHAR(30), SALARIES_BENEFITS VARCHAR(30),GRADUATE_ASSISTANT VARCHAR(30),OPS VARCHAR(30), EXPENSES VARCHAR(30), T_OUT VARCHAR(30), CONSTRAINT PK_OPERATINGFUND PRIMARY KEY (ROLE, ID, SMARTTAG));

CREATE TABLE fauAMP (ID INT, ROLE VARCHAR(30), POSITION_NUMBER VARCHAR(30), POSITION_TITLE VARCHAR(30), FTE VARCHAR(30), ANNUAL_RATE VARCHAR(30), STATE VARCHAR(30),  FOREIGN KEY (ID,ROLE) REFERENCES DOCS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_FAUAMP PRIMARY KEY (ID, ROLE, POSITION_TITLE));

CREATE TABLE fauSP (ID INT, ROLE VARCHAR(30), POSITION_NUMBER VARCHAR(30), POSITION_TITLE VARCHAR(30), FTE VARCHAR(30), ANNUAL_RATE VARCHAR(30), STATE VARCHAR(30),  FOREIGN KEY (ID,ROLE) REFERENCES DOCS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_FAUAMP PRIMARY KEY (ID, ROLE, POSITION_TITLE));

CREATE TABLE fauOPS (ID INT,ROLE VARCHAR(55), TITLE VARCHAR(50), FAUSTUDENT VARCHAR(3), HOURLYRATE VARCHAR(9), HOURS_WEEK VARCHAR(9), WEEKS_YEAR VARCHAR(9),PEOPLE_IN_POSITION VARCHAR(9), FOREIGN KEY (ID,ROLE) REFERENCES DOCS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_FAUOPS PRIMARY KEY (ID, TITLE));

CREATE TABLE fauOPSGA (ID INT,ROLE VARCHAR(55), TITLE VARCHAR(50),HOURLYRATE VARCHAR(9), HOURS_WEEK VARCHAR(9), WEEKS_YEAR VARCHAR(9), FOREIGN KEY (ID,ROLE) REFERENCES DOCS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_FAUOPS PRIMARY KEY (ID, TITLE));

CREATE TABLE FAUExpenses (ID INT, ROLE VARCHAR(30), NAME VARCHAR(50), AMOUNT VARCHAR(9), FOREIGN KEY (ID,ROLE) REFERENCES DOCS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_FAUEXPENSES PRIMARY KEY (ID, ROLE, NAME));

CREATE TABLE FAUComments (ID INT, ROLE VARCHAR(30), Subject VARCHAR(30), Comment VARCHAR(255), FOREIGN KEY (ID,ROLE) REFERENCES DOCS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_FAUEXPENSES PRIMARY KEY (ID, ROLE, Subject));


CREATE TABLE FAUT_OUT (ID INT, ROLE VARCHAR(30), SUBJECT VARCHAR(30), AMOUNT VARCHAR(9), FOREIGN KEY (ID,ROLE) REFERENCES DOCS(ROLE,ID) ON DELETE CASCADE, CONSTRAINT PK_FAUEXPENSES PRIMARY KEY (ID, ROLE, SUBJECT));
